PCS for another operation is in progress error
redkubes/redkubes.github.io pull request #1
Opened 2021-03-26 15:32 UTC by j-zimnowoda

2021-03-26 16:10 UTC, Morriz requested changes
tnx...bit sloppy tho:
- two H4's
- your section should replace the old helm error

2021-03-30 10:03 UTC, Morriz commented
Can you please add "fixes #${issue_number}" to descriptions of pull requests @j-zimnowoda ? Then these get connected and don't show up in the backlog...

2021-03-31 07:55 UTC, Dunky13 approved these changes

2021-04-01 18:33 UTC, Morriz commented
Can you please wrap this up @j-zimnowoda ?

2021-04-07 11:32 UTC, svatwork requested changes
I put AND in capital so users won't read over it, but feel free to remove that suggestion. But let's not skip articles (the, a, an).

2021-04-07 11:32 UTC, svatwork commented on docs/ki-cli.md
> +Otherwise, if there is helm realease in `pending` state and it has only one revision, then remove that release:
```suggestion
Otherwise, if there is an helm release in the state `pending` AND it has only one revision, then remove that release:
```

2021-04-07 11:32 UTC, svatwork commented on docs/ki-cli.md
> +If there is helm release in `pending` state and it has more than one revision, then rollback to the previous revision:
```suggestion
If there is an helm release in the state `pending` AND it has more than one revision, then rollback to the previous revision:
```

2021-04-09 08:58 UTC, Morriz commented
Hello?

2021-04-13 12:43 UTC, j-zimnowoda commented
> Can you please add "fixes #${issue_number}" to descriptions of pull requests @j-zimnowoda ? Then these get connected and don't show up in the backlog...

There is no issue for that. It comes directly from slack discussion

2021-04-13 12:44 UTC, j-zimnowoda commented
> tnx...bit sloppy tho:
> 
> * two H4's
> * your section should replace the old helm error

This is a different error

2021-04-14 07:18 UTC, j-zimnowoda commented on docs/ki-cli.md
> +If there is helm release in `pending` state and it has more than one revision, then rollback to the previous revision:
done

2021-04-15 02:09 UTC, Morriz requested changes
one char...lol

2021-04-15 02:09 UTC, Morriz commented on docs/ki-cli.md
> +Otherwise, if there is an helm release in the state `pending` AND it has only one revision, then remove that release:
```suggestion
Otherwise, if there is a helm release in the state `pending` AND it has only one revision, then remove that release:
```

2021-04-15 07:12 UTC, svatwork approved these changes

2021-04-16 09:01 UTC, Morriz approved these changes

2021-04-16 09:02 UTC, merged