feat: update gitea teams info
redkubes/redkubes.github.io pull request #29
Opened 2023-09-22 07:31 UTC by ElderMatt

This PR updates the information about needing to add users as collaborators. With the new changes this is not needed any longer.

[See Issue](https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/otomi-core/1257)

2023-09-22 07:50 UTC, j-zimnowoda requested changes

2023-09-22 07:50 UTC, j-zimnowoda commented on docs/apps/gitea.md
> +Currently Gitea only supports a single role in combination with OIDC. To sign in to Gitea, a user needs to be a member of the `team-admin` group.
This is not true. It is enough that you are a team member, isn't it?

2023-10-02 09:00 UTC, ferruhcihan approved these changes
LGTM

2023-10-03 08:20 UTC, j-zimnowoda approved these changes

2023-10-03 08:20 UTC, merged